### PR TITLE
Rewrite gem to perform placeholder replacement in Rack middleware

### PR DESCRIPTION
**Pull request by BRMatt**
The original after_filter implementation doesn't work if the response is 
generated in a before_filter, as rails will not process the action/after 
filters.

This also has the side effect of not making the gem rails specific and in
theory this could now be used with sinatra/other rack compatible frameworks.

### CODE REVIEW

**Comment by cmer** [comment]
This is quite the rewrite!

Give me some time to look into it and test more, but it seems to make a lot of sense.

One concern though, how do we ensure that this is inserted before rack-cache?

**Comment by BRMatt** [comment]
Thanks, but after thinking about it for a bit this should really have some tests before it gets merged. Maybe an end-to-end test against a test app that makes sure the token is getting replaced?

> One concern though, how do we ensure that this is inserted before rack-cache?

That might be hard to do, I _seem_ to remember the object Railties use to modify the middleware stack doesn't have an unshift operator. The user could always unshift the middleware themselves.

**Comment by faheemmughal** [comment]
:+1:

**Comment by eturino** [comment]
@BRMatt @cmer what's the status on the rewrite?

**Comment by BRMatt** [comment]
@eturino I no longer work for the company that I wrote this for. From what I remember the rewrite works fine (the company was using it in production), it just doesn't have tests to verify that the behaviour works as expected.

**Pull request closed without merging**
